#!/usr/bin/env ruby

require 'yaml'
require 'find'

bupfile = YAML.load_file('Bup')
environment = ARGV[0]
command = ARGV[1]
host = bupfile[environment]
app_name = bupfile["app_name"]

# private_key = bupfile["private_key"]
# private_key = ""

# Dir.glob("#{Dir.home}/.ssh/*").each do |key|
#   puts key
#   # key_path = "#{Dir.home}/.ssh/#{key}"
#   system "ssh -i #{key} -q ubuntu@#{host} exit"
#   connected = system "echo $?"
#   if connected != 255
#     private_key = key
#     break
#   end  
# end

if environment == "vagrant"
  vagrant_directory = ""
  Find.find(".") do |path|
    Find.prune if path.include? '.git'
    next unless File.directory?(path)
    if path.include? '.vagrant'
      vagrant_directory = path
      break
    end
  end
  command = command || "ssh"
  exec "pushd .; cd #{vagrant_directory}/../; vagrant #{command}; popd"
elsif command == "console"
  exec "ssh ubuntu@#{host} -t 'bash -l -c \"cd /#{app_name}/current; rails c; bash\"'"
elsif command == "update"
  exec "sh railsbox/#{environment}/update.sh"
elsif command == "logs"
  exec "ssh ubuntu@#{host} -t 'bash -l -c \"tail -f /#{app_name}/shared/log/puma.#{environment}.log\"'"
elsif command == "restart"
  exec "ssh ubuntu@#{host} sudo restart #{app_name}"
elsif command == "reindex"
  exec "ssh ubuntu@#{host} -t 'bash -l -c \"cd /#{app_name}/current; rake searchkick:reindex:all\"'"
else
  exec "ssh ubuntu@#{host}"
end